[package]
name = "ctenv"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
dotenvy = "0.15"

[dev-dependencies]
trybuild = "1.0.105"
